osx_image: xcode9.2

language: objective-c

#xcode_project: eXo.xcodeproj
xcode_workspace: eXo.xcworkspace

xcode_scheme: eXo

script: pod update && xcodebuild clean && xcodebuild build -sdk iphonesimulator -workspace eXo.xcworkspace -scheme eXo CODE_SIGNING_REQUIRED=NO
