"project_id" : "CROWDIN_PROJECT_ID"
"api_token" : "CROWDIN_PERSONAL_TOKEN"
"base_path" : "."
"base_url" : "https://api.crowdin.com"
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

"preserve_hierarchy": true
"upload_translations": false

#
# Files configuration
#
files: [
 {
  "source" : "/eXo/Resources/en.lproj/Localizable.strings",
  "dest": "/mobile/ios/Localizable.strings",
  "translation" : "/eXo/Resources/%osx_code%/Localizable.strings",
 },
 {
  "source" : "/share-extension/en.lproj/Localizable.strings",
  "dest": "/mobile/ios/share-extension/Localizable.strings",
  "translation" : "/share-extension/%osx_code%/Localizable.strings",
 }
]