# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.37.0"

default_platform :ios

platform :ios do

### BEFORE ALL

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    # cocoapods
    
    # increment_build_number
  end

### BUILD & TEST

  desc "Run all the tests"
  lane :test do
    # snapshot
    scan(
        workspace: "eXo.xcworkspace",
        scheme: "eXo",
        clean: true
    )
  end

### BUILD & BUNDLE IPA

  desc "Create a new Adhoc Bundle (IPA)"
  desc "This will also make sure the provisioning profile is up to date"
  lane :adhoc do
    # snapshot
    sigh(
        output_path:"/tmp",
        adhoc:true
    )
    gym(
        scheme: "eXo",
        output_directory:"/tmp"
    )

    # pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

### AFTER ALL

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
