# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
   "iPhone 6",
   "iPhone 4s",
   "iPad Retina"
#   "iPhone 5",
#   "iPhone 6 Plus",
#   "iPad Pro"
])

languages([
  "en-US"
#  "fr-FR"
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch_arguments
# launch_arguments("-favColor red")

# The name of the scheme which contains the UI Tests
scheme "eXoSnapshots"

# Where should the resulting screenshots be stored?
# output_directory "./screenshots"

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots true

# Choose which project/workspace to use
# project "./Project.xcodeproj"
workspace "./eXo.xcworkspace"

# For more information about all available options run
# snapshot --help
