name: iOS Build

on:
  pull_request:
    branches: [ develop, acceptance ]
env: 
  BUNDLE_ID: 'org.exoplatform.exo-snapshot'
jobs:
  build:
    name: CI Build eXo iOS Project
    runs-on: macos-12
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          token: ${{ secrets.ADMIN_TOKEN }}
      - name: Setup Xcode 14
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2'
      - name: Refresh podfile
        run: rm -v Podfile.lock && pod install && git add -A && git -c user.name='eXo Software Factory' -c user.email='exo-swf@exoplatform.com' commit -m 'Update podfile.lock' && git fetch && git push origin HEAD:refs/heads/testbuild13-2