name: iOS Build

on:
  pull_request:
    branches: [ develop, acceptance ]
env: 
  BUNDLE_ID: 'org.exoplatform.exo-snapshot'
jobs:
  build:
    name: CI Build eXo iOS Project
    runs-on: macos-12
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Xcode 14
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2'
      # Use SSH Key to gather certificate from a private Github repository. Use a dedicated on is recommended.
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      # Setup Ruby 3.0
      - name: Setup ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
     # Cache Ruby gems
      - name: Cache Ruby gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      # Cache CocoaPods
      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      # Install Bundler and dependencies gems
      - name: Install bundler and dependencies
        run: gem install bundler && bundle install 
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3.11
