name: Sync Crowdin with eXo Mobile Project
on:
  schedule:
    - cron:  '0 22 * * *' # Everyday at 10 PM UTC
  workflow_dispatch:
  workflow_call:
env:
  CROWDIN_SYNC_BRANCH: 'integration/6.2.x'
  BASE_BRANCH: 'acceptance'

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ env.BASE_BRANCH }}
        fetch-depth: 0
    - name: Cleanup Crowdin Sync Branch
      run: |
        git push origin :${CROWDIN_SYNC_BRANCH} ||:
        git branch -D ${CROWDIN_SYNC_BRANCH} ||:
    - name: Mark workspace as safe folder
      run: git config --global --add safe.directory /github/workspace
    - name: Synchronize crowdin with the project
      uses: crowdin/github-action@1.5.1
      with:
        upload_translations: false
        download_translations: true
        localization_branch_name: ${{ env.CROWDIN_SYNC_BRANCH }}
        create_pull_request: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}