name: Merge Crowdin translation to eXo Mobile Project
on:
  schedule:
    - cron:  '0 0 * * 4' # Thu at 0 AM UTC
  workflow_dispatch:
env:
  CROWDIN_SYNC_BRANCH: 'integration/6.2.x'
  BASE_BRANCH: 'acceptance'

jobs:
  # Sync phase is mandatory before the Merge job
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ env.BASE_BRANCH }}
        fetch-depth: 0
    - name: Cleanup Crowdin Sync Branch
      run: |
        git push origin :${CROWDIN_SYNC_BRANCH} ||:
        git branch -D ${CROWDIN_SYNC_BRANCH} ||:
    - name: Synchronize crowdin with the project
      uses: crowdin/github-action@1.4.4
      with:
        upload_translations: true
        download_translations: true
        localization_branch_name: ${{ env.CROWDIN_SYNC_BRANCH }}
        create_pull_request: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

  merge-crowdin-translation:
    needs: synchronize-with-crowdin
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ env.BASE_BRANCH }}
        token: ${{ secrets.ADMIN_TOKEN }}
        fetch-depth: 0
    - name: Merge Crowdin Translation to the base branch
      run: |
        git fetch
        git merge --squash origin/${CROWDIN_SYNC_BRANCH}
        git -c user.name='eXo Software Factory' -c user.email='exo-swf@exoplatform.com' commit -m 'Merge Translations'
    - name: Push changes to base branch
      run: git push origin ${BASE_BRANCH}:${BASE_BRANCH}