name: Rebase acceptance branch

on:
  push:
    branches: [develop]
jobs:
  rebase:
    name: Rebase acceptance branch with develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_TOKEN }}
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.SWF_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.SWF_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Rebase branch
        run: |
          git config --global user.email "exo-swf@exoplatform.com"
          git config --global user.name "eXo Software Factory"
          git pull 
          git checkout acceptance
          git rebase develop && git push origin acceptance:acceptance --force-with-lease
